### ISSUE TITLE
False negative when invalid token is used

### ISSUE THREAD

**Issue by jvandermeulen** [mcapra/nagios-check_nls_commands#2]
Matthew,

Noticed that the API token provided by "-k" is not verified. Even providing a non-existing API key leads to an OK state, thus a false negative.
Here's an example of problem situation with a proper token.

```
[nagios@nagiosxi ~]$ php /usr/local/nagios/libexec/check_nls_commands.php -a naglog-prod.asz.int -k 57c564f0c2673941eee9acfeedd26363d08c9bfd -w 172800 -c 259200
CRITICAL - Stale commands: backup_maintenance

```
And when an non-existing token is provided (in this case _00_)
```
[nagios@nagiosxi ~]$ php /usr/local/nagios/libexec/check_nls_commands.php -a naglog-prod.asz.int -k 00 -w 172800 -c 259200
OK - All commands found and have run recently.
```

**Comment by mcapra** [comment]
I believe I have fixed this issue in this commit: https://github.com/mcapra/nagios-check_nls_commands/commit/55d2adff9f3f2e029bb97818325c8ec9776d7e42

**Comment by jvandermeulen** [comment]
Thanks a lot, indeed you fixed it. I sent you a PR to bump the version number!
